services:
  pig:
    build: .
    container_name: report-service
    ports:
    - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: auditorium_db
      RABBITMQ_URL: amqp://guest:guest@localhost:5672/
      QUEUE_NAME: camera_events
      GIN_MODE: debug
      SERVER_PORT: 8080
    networks:
      - tyk-network
    restart: unless-stopped

networks:
  tyk-network:
    external: true