services:
  pig:
    build: .
    container_name: report-service
    ports:
    - "8080:8080"
    environment:
      DB_HOST: postgres
    networks:
      - tyk-network
    restart: unless-stopped

networks:
  tyk-network:
    external: true